apiVersion: v1
kind: ConfigMap
metadata:
  name: refoza-config
  namespace: refoza
data:
  NODE_ENV: "production"
  PORT: "5000"
  HOST_BASE: "*.tenant.refoza.com"
  CLIENT_URL_BASE: "https://*.tenant.refoza.com"
  CLIENT_PROTOCOL: "https"
  CLIENT_PORT: "443"
  CORS_DOMAIN_SUFFIX: ".tenant.refoza.com"
  BILLING_SITE_URL: "https://subscription.refoza.com"
  NEXT_PUBLIC_API_BASE_URL: "https://*.tenant.refoza.com"
  NEXT_PUBLIC_SITE_HOST: "https://*.tenant.refoza.com"
  NEXT_PUBLIC_BILLING_HOST: "subscription.refoza.com"
  NEXT_PUBLIC_TENANT_HOST_BASE: "tenant.refoza.com"
