apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: refoza-backend-hpa
  namespace: refoza
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: refoza-backend
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: refoza-frontend-hpa
  namespace: refoza
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: refoza-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
